enum Action {
    FETCH_ARTICLIES_LOADING = "FETCH_ARTICLIES_LOADING",
    FETCH_ARTICLIES_SUCCESS = "FETCH_ARTICLIES_SUCCESS",
    FETCH_ARTICLIES_ERROR = "FETCH_ARTICLIES_ERROR",
    SET_PAGE = "SET_PAGE"
}

export default Action;
