enum Action {
    FETCH_ARTICLIE_LOADING = "FETCH_ARTICLIES_LOADING",
    FETCH_ARTICLIE_SUCCESS = "FETCH_ARTICLIES_SUCCESS",
    FETCH_ARTICLIE_ERROR = "FETCH_ARTICLIES_ERROR",
    ADD_COMMENT = "ADD_COMMENT",
    MODIFY_COMMENT = "MODIFY_COMMENT",
    DELETE_COMMENT = "DELETE_COMMENT",
}

export default Action;
